export const dmmf = {
  datamodel: {
    models: [
      {
        name: "User",
        dbName: null,
        schema: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            nativeType: null,
            default: { name: "autoincrement", args: [] },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "email",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "name",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "posts",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            nativeType: null,
            relationName: "PostToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "profile",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Profile",
            nativeType: null,
            relationName: "ProfileToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "comments",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            nativeType: null,
            relationName: "CommentToUser",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Post",
        dbName: null,
        schema: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            nativeType: null,
            default: { name: "autoincrement", args: [] },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            nativeType: null,
            default: { name: "now", args: [] },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: true,
          },
          {
            name: "published",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Boolean",
            nativeType: null,
            default: false,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "title",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "content",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "deleted",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Boolean",
            nativeType: null,
            default: false,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            nativeType: null,
            relationName: "PostToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            relationOnDelete: "Cascade",
            relationOnUpdate: "Cascade",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "comments",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            nativeType: null,
            relationName: "CommentToPost",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Comment",
        dbName: null,
        schema: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            nativeType: null,
            default: { name: "autoincrement", args: [] },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "createdAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "DateTime",
            nativeType: null,
            default: { name: "now", args: [] },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "updatedAt",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "DateTime",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: true,
          },
          {
            name: "content",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "author",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            nativeType: null,
            relationName: "CommentToUser",
            relationFromFields: ["authorId"],
            relationToFields: ["id"],
            relationOnDelete: "Cascade",
            relationOnUpdate: "Cascade",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "authorId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "post",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Post",
            nativeType: null,
            relationName: "CommentToPost",
            relationFromFields: ["postId"],
            relationToFields: ["id"],
            relationOnDelete: "Cascade",
            relationOnUpdate: "Cascade",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "postId",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "repliedTo",
            kind: "object",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            nativeType: null,
            relationName: "replies",
            relationFromFields: ["repliedToId"],
            relationToFields: ["id"],
            relationOnDelete: "Cascade",
            relationOnUpdate: "Cascade",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "repliedToId",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "replies",
            kind: "object",
            isList: true,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Comment",
            nativeType: null,
            relationName: "replies",
            relationFromFields: [],
            relationToFields: [],
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
      {
        name: "Profile",
        dbName: null,
        schema: null,
        fields: [
          {
            name: "id",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: true,
            isReadOnly: false,
            hasDefaultValue: true,
            type: "Int",
            nativeType: null,
            default: { name: "autoincrement", args: [] },
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "bio",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "String",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "age",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Int",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "user",
            kind: "object",
            isList: false,
            isRequired: true,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "User",
            nativeType: null,
            relationName: "ProfileToUser",
            relationFromFields: ["userId"],
            relationToFields: ["id"],
            relationOnDelete: "Cascade",
            relationOnUpdate: "Cascade",
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "userId",
            kind: "scalar",
            isList: false,
            isRequired: true,
            isUnique: true,
            isId: false,
            isReadOnly: true,
            hasDefaultValue: false,
            type: "Int",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
          {
            name: "meta",
            kind: "scalar",
            isList: false,
            isRequired: false,
            isUnique: false,
            isId: false,
            isReadOnly: false,
            hasDefaultValue: false,
            type: "Json",
            nativeType: null,
            isGenerated: false,
            isUpdatedAt: false,
          },
        ],
        primaryKey: null,
        uniqueFields: [],
        uniqueIndexes: [],
        isGenerated: false,
      },
    ],
  },
};
