services:
  postgres:
    image: "postgres:18.3"
    hostname: postgres
    user: postgres
    restart: always
    environment:
      - POSTGRES_DATABASE=test
      - POSTGRES_PASSWORD=postgrespass
    ports:
      - '5433:5432'
