name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-slim

    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run lint
        run: biome ci --reporter=github
