name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespass
          POSTGRES_DB: test
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      DATABASE_URL: postgres://postgres:postgrespass@localhost:5433/test

    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test:ci
        working-directory: test
