name: Typecheck

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Check types
        run: yarn typecheck
